/**
 * ATROSA Delivery Channels — Console, file, Slack, GitHub, Jira
 */

import fs from "node:fs";
import http from "node:http";
import https from "node:https";
import { URL } from "node:url";
import { execFileSync } from "node:child_process";
import { REQUESTS_LOG_PATH } from "../utils/paths.js";
import type { ObservabilityReq } from "./requests.js";

export class DeliveryChannel {
  static deliver(request: ObservabilityReq, channels: string[]): void {
    for (const channel of channels) {
      switch (channel) {
        case "console":
          DeliveryChannel.toConsole(request);
          break;
        case "slack":
          DeliveryChannel.toSlack(request);
          break;
        case "github":
          DeliveryChannel.toGithubIssue(request);
          break;
        case "jira":
          DeliveryChannel.toJira(request);
          break;
        case "file":
          DeliveryChannel.toFile(request);
          break;
      }
    }
  }

  private static toConsole(req: ObservabilityReq): void {
    const severityIcons: Record<string, string> = {
      critical: "[!!!]",
      high: "[!!]",
      medium: "[!]",
      low: "[i]",
    };
    const icon = severityIcons[req.severity] ?? "[?]";
    console.log(`\n  ${icon} ${req.request_id} (${req.severity.toUpperCase()})`);
    console.log(`      Source: ${req.source}`);
    console.log(`      Field: ${req.field}`);
    console.log(`      Detail: ${req.detail}`);
    console.log(`      Action: ${req.action_required}`);
  }

  private static toSlack(req: ObservabilityReq): void {
    const url = process.env.TELEMETRY_SLACK_WEBHOOK;
    if (!url) {
      console.log(
        "  [SLACK] TELEMETRY_SLACK_WEBHOOK not set — skipping Slack delivery",
      );
      return;
    }

    const severityEmoji: Record<string, string> = {
      critical: ":red_circle:",
      high: ":large_orange_circle:",
      medium: ":large_yellow_circle:",
      low: ":white_circle:",
    };
    const emoji = severityEmoji[req.severity] ?? ":question:";

    const text =
      `${emoji} *ATROSA Telemetry Request — ${req.request_id}*\n` +
      `*Severity:* ${req.severity.toUpperCase()}\n` +
      `*Source:* \`${req.source}\`\n` +
      `*Field:* \`${req.field}\`\n` +
      `*Detail:* ${req.detail}\n` +
      `*Action Required:* ${req.action_required}\n` +
      `_Resolve with:_ \`atrosa telemetry resolve ${req.request_id}\``;

    postJson(url, { text })
      .then((status) => console.log(`  [SLACK] Sent ${req.request_id} -> ${status}`))
      .catch((err) => console.log(`  [SLACK] Failed: ${err}`));
  }

  private static toGithubIssue(req: ObservabilityReq): void {
    const repo = process.env.TELEMETRY_GITHUB_REPO;
    if (!repo) {
      console.log("  [GITHUB] TELEMETRY_GITHUB_REPO not set — skipping");
      return;
    }

    const title = `[ATROSA] ${req.request_id}: Add '${req.field}' to ${req.source}`;
    const body =
      `## Telemetry Gap Report\n\n` +
      `**Request ID:** \`${req.request_id}\`\n` +
      `**Severity:** ${req.severity.toUpperCase()}\n` +
      `**Source:** \`${req.source}\`\n` +
      `**Field:** \`${req.field}\`\n\n` +
      `### Detail\n${req.detail}\n\n` +
      `### Action Required\n${req.action_required}\n\n` +
      `### Context\n${req.hunt_context || "N/A"}\n\n` +
      `---\n_Generated by ATROSA Telemetry Engineer_`;

    try {
      const result = execFileSync(
        "gh",
        [
          "issue",
          "create",
          "--repo",
          repo,
          "--title",
          title,
          "--body",
          body,
          "--label",
          `telemetry,${req.severity}`,
        ],
        { encoding: "utf-8", timeout: 15_000 },
      );
      console.log(`  [GITHUB] Created issue: ${result.trim()}`);
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      console.log(`  [GITHUB] Failed: ${errMsg.slice(0, 200)}`);
    }
  }

  private static toJira(req: ObservabilityReq): void {
    const jiraUrl = process.env.TELEMETRY_JIRA_URL;
    const jiraToken = process.env.TELEMETRY_JIRA_TOKEN;
    const jiraProject = process.env.TELEMETRY_JIRA_PROJECT;

    if (!jiraUrl || !jiraToken || !jiraProject) {
      console.log(
        "  [JIRA] TELEMETRY_JIRA_URL/TOKEN/PROJECT not set — skipping",
      );
      return;
    }

    const priorityMap: Record<string, string> = {
      critical: "Highest",
      high: "High",
      medium: "Medium",
      low: "Low",
    };

    const payload = {
      fields: {
        project: { key: jiraProject },
        summary: `[ATROSA] ${req.request_id}: Add '${req.field}' to ${req.source}`,
        description:
          `h2. Telemetry Gap Report\n\n` +
          `*Request ID:* ${req.request_id}\n` +
          `*Severity:* ${req.severity.toUpperCase()}\n` +
          `*Source:* ${req.source}\n` +
          `*Field:* ${req.field}\n\n` +
          `h3. Detail\n${req.detail}\n\n` +
          `h3. Action Required\n${req.action_required}`,
        issuetype: { name: "Task" },
        priority: { name: priorityMap[req.severity] ?? "Medium" },
      },
    };

    const auth = Buffer.from(jiraToken).toString("base64");
    const apiUrl = `${jiraUrl}/rest/api/2/issue`;

    postJson(apiUrl, payload, { Authorization: `Basic ${auth}` })
      .then(() => console.log(`  [JIRA] Created issue`))
      .catch((err) => console.log(`  [JIRA] Failed: ${err}`));
  }

  private static toFile(req: ObservabilityReq): void {
    fs.appendFileSync(
      REQUESTS_LOG_PATH,
      JSON.stringify(req) + "\n",
      "utf-8",
    );
    console.log(`  [FILE] Appended to ${REQUESTS_LOG_PATH}`);
  }
}

function postJson(
  url: string,
  data: unknown,
  extraHeaders?: Record<string, string>,
): Promise<number> {
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    const payload = JSON.stringify(data);
    const lib = parsed.protocol === "https:" ? https : http;
    const req = lib.request(
      parsed,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(payload),
          ...(extraHeaders ?? {}),
        },
        timeout: 10_000,
      },
      (res) => resolve(res.statusCode ?? 0),
    );
    req.on("error", reject);
    req.write(payload);
    req.end();
  });
}
